### PR TITLE
 refactor:autolink rule

### PR DESCRIPTION
**Pull request by LinFeng1997**

### CODE REVIEW

**Comment by puzrin** [comment]
Please, don't PR here incomplete things and without explanation why change needed.

**Comment by LinFeng1997** [comment]
@puzrin I want to make this piece of code more readable,thank you

**Comment by puzrin** [comment]
1. Your code has inlined functions, that will cause performance loss.
2. Existing code is good enough, no changes needed. Please avoid changes "just for fun".

**Comment by LinFeng1997** [comment]
@puzrin 
1. I agree with you that inline functions do cause a little loss of performance.
2. I think the code for AUTO_LINK and EMAIL_LINK is duplicated, this should be extracted as a function

**Comment by puzrin** [comment]
Sorry, i don't agree. This code is good as is.

**Comment by LinFeng1997** [comment]
@puzrin Well, you're the master of this code, but I'm still insisting that the logic for dealing with AUTO-LINK and EMAIL-LINK should be extracted as a function.

**Pull request closed without merging**
