### PR TITLE
fix(rules/fence): trim info trailling whitespaces

### PR DESCRIPTION
**Pull request by moki**
trim trailling whitespaces from info field of the fence token

### CODE REVIEW

**Comment by rlidwka** [comment]
Can you please clarify why is it needed?

**Comment by rlidwka** [comment]
Can you please clarify why is it needed?

**Comment by moki** [comment]
leaving as it is, this code:

```
'''js____
console.log('hello, world');
'''
```
where

**'** means **`**
and
**_** means **whitespace**


would be parsed as:
```
Token {
    type: 'fence',
    info: 'js    '
}
```

parsing trailing whitespaces as part of the info field.

whatever is the pipeline you put parser in, one would get unnecessary data inside info field.

As an example i have a pipeline, where i feed `info`(which is programming language name) into library to make a decision
about how to render code, and that leads to an error `unknown language js____`.

where **_** means **whitespace**

**Comment by rlidwka** [comment]
merged in https://github.com/markdown-it/markdown-it/commit/67fa0f239752ec649a3e93fe8bd7a3f410fec0f3 (with added changelog)

**Comment by rlidwka** [comment]
nvm, reverted for now, not sure if breaking change is worth it

**Comment by puzrin** [comment]
This change is breaking, and we should force trailing spaces to drop everywhere. The concrete example can be solved via renderer, without touching everything else.

**Pull request closed without merging**
