### PR TITLE
better check for property 'references' in js object

### PR DESCRIPTION
**Pull request by kospl**
fix for javascript error 'Cannot read property "references" from
undefined'

### CODE REVIEW

**Comment by puzrin** [comment]
I don't like this PR. It adds tons of checks for param that is mandatory.

**Comment by kospl** [comment]
Maybe I'm wrong, but I don't see any sign that env param is mandatory.

For example Google skips it successfully in their example: https://github.com/googlesamples/md2googleslides/blob/master/src/extract_slides.js#L80
which leads to `Cannot read property "references" from undefined` in some cases. 
I just added this check for those cases.

Maybe there's better solution for this problem, I cannot disagree.

**Comment by puzrin** [comment]
I'm not author of that code and have no ideas why it's done such way. Probably that's a bug.

See docs https://markdown-it.github.io/markdown-it/#MarkdownIt.parse. It never says that param is optional and explains what should be passed.

**Comment by puzrin** [comment]
Also see #351

**Comment by kospl** [comment]
I see docs say it is mandatory, but it never checked in code for being undefined. That should be fixed. 
Is it ok to add `env = env || {};` to `MarkdownIt.prototype.parse` like it's done in `MarkdownIt.prototype.render`?

**Comment by puzrin** [comment]
No. This parameter is optional in `.render()` but mandatory in `.parse()`.

**Comment by kospl** [comment]
Then maybe 
`
  if (typeof env === 'undefined') {
    throw new Error('env parameter is mandatory');
  }
`
?

**Comment by puzrin** [comment]
You try to discuss how to change things prior to decide iif those changes are needed or not.

I think that's not critical and i don't like to change code just for fun. See #351.

**Comment by digitalmoksha** [comment]
I have to agree with @kospl on this one:  is the guard required? no.  Is it good practice, defensive programming?  yes.  particularly for a public entry point.  And while it may be mentioned in the docs, documentation can usually be dense to read.  So I think the guard is useful.

**Comment by puzrin** [comment]
@digitalmoksha but `.parse()` is a low level API, not expected to be called by regular users. It's even hidden in readme. And `.render()` has some additional checks.

**Comment by digitalmoksha** [comment]
@puzrin You're right, `parse` is marked internal, and so my previous comment doesn't really apply.

**Comment by puzrin** [comment]
Close as dupe of #351 &  to avoid open issues/pr with "endless" time.

It's already labeled to be search-able sometime later. If new info about "how this bug happen" appears, feel free to update.

This issue can be revived anytime when more arguments appear.

**Pull request closed without merging**
