### PR TITLE
Removed bower

### PR DESCRIPTION
**Pull request by nainardev**
Bower is deprecated long time ago https://bower.io

### CODE REVIEW

**Comment by puzrin** [comment]
Reasons? I don't see any visual changes.

**Comment by nainardev** [comment]
Bower is deprecated long time ago https://bower.io

**Comment by puzrin** [comment]
Ah, ok. But then more cleanup needed. I will do that myself, but keep this PR open as reminder.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/commit/446bbcf9983c8884a5dba553eb023d6e16e97277

**Pull request closed without merging**
