### PR TITLE
Don't split cells on pipe characters inside backticks.

### PR DESCRIPTION
**Pull request by jbt**
This is for #86. As I said over there I'm not _entirely_ sure whether this should be considered the correct behaviour, but if it is, then this addresses that.

### CODE REVIEW

**Comment by puzrin** [comment]
Looks nice. Could you add one more test - what happens if backtick is opened but not closed?

This patch in theory can do something strange if i place url with backtick into table cell, but i don't think this ever happens in real life.

**Comment by jbt** [comment]
Oh that's a good point actually, I don't quite know what should happen there. GitHub is a bit weird in that case:

```
 A |  B  | C 
---|-----|---
 1 | `| | 3
```

produces...

 A |  B  | C 
---|-----|---
 1 | `| | 3


but

```
 A |  B  | C 
---|-----|---
 1 | ` | | 3
```

(with extra space) produces...

 A |  B  | C 
---|-----|---
 1 | ` | | 3


I'll have a look and see if I can figure out the best way of dealing with that. I don't actually understand why the first case behaves as it does - I'd have thought it should behave like the second case both times.

If it comes to it, does it matter if the first case isn't treated exactly the same as how GitHub does it?

**Comment by puzrin** [comment]
I think, it's not principle to do 100% as gothub does. IMHO, if backtick is not closed, it worth consider it as usual char (as for text without any table)

**Comment by jbt** [comment]
Ok then, I've got another change and test-case that I'll commit and push now

**Comment by puzrin** [comment]
Also, it worth to properly handle escaping for that:

```
\\\`|\\\` => two rows "\`" 
```

**Comment by jbt** [comment]
Ok, I added treatment for the unclosed-backtick case, as well as a test for the escaping example you mentioned

**Comment by puzrin** [comment]
could you squash to single commit?

**Comment by jbt** [comment]
There, all squashed :)

**Comment by puzrin** [comment]
Published. Thanks a lot for PR!

**Pull request merged**
