### PR TITLE
Feature/fixtures for em strong

### PR DESCRIPTION
**Pull request by AlexanderSergan**
### Overview:
Created test cases for according to #561. Test cases with full word wrap works good, but partial word-wrapping don't. Tests are consistent with commonmark [demo](https://spec.commonmark.org/dingus/?text=%23%23%20Full%20word%20wrap%3A%0A%0A***italicbold***%20%20%60%3C--%20OK%60%0A%0A_**italicbold**_%20%20%60%3C--%20OK%60%0A%0A**_italicbold_**%20%20%60%3C--%20OK%60%0A%0A%23%23%20Inside%20word%20wrap%3A%0A%0Aita***licbo***ld%20%20%60%3C--%20FAIL%20in%20MarkdownIt%2C%20OK%20here%60%0A%0Aita_**licbo**_ld%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%0A%0Aita**_licbo_**ld%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%0A%0A%23%23%20At%20start%20of%20the%20word%3A%0A%0A***italic***bold%20%20%60%3C--%20FAIL%20in%20MarkdownIt%2C%20OK%20here%60%0A%0A_**italic**_bold%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%0A%0A**_italic_**bold%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%0A%0A%23%23%20At%20end%20of%20the%20word%3A%0A%0Aitalic***bold***%20%20%60%3C--%20FAIL%20in%20MarkdownIt%2C%20OK%20here%60%0A%0Aitalic_**bold**_%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%0A%0Aitalic**_bold_**%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%0A). @puzrin please check out if it is correct and let's create issue for this or add `bug` label to the original issue? Thanks.

### Motivation
This PR is created to show inconsistency of markdown-it and commonmark. Demos: markdown-it [demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20Bold%2Fitalic%20word%20wrap%20issues%20demo%5Cn%5Cn%23%23%20Full%20word%20wrap%3A%5Cn%5Cn%2A%2A%2Aitalicbold%2A%2A%2A%20%20%60%3C--%20OK%60%5Cn%5Cn_%2A%2Aitalicbold%2A%2A_%20%20%60%3C--%20OK%60%5Cn%5Cn%2A%2A_italicbold_%2A%2A%20%20%60%3C--%20OK%60%5Cn%5Cn%23%23%20Inside%20word%20wrap%3A%5Cn%5Cnita%2A%2A%2Alicbo%2A%2A%2Ald%20%20%60%3C--%20NONE%60%5Cn%5Cnita_%2A%2Alicbo%2A%2A_ld%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%5Cn%5Cnita%2A%2A_licbo_%2A%2Ald%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%5Cn%5Cn%23%23%20At%20start%20of%20the%20word%3A%5Cn%5Cn%2A%2A%2Aitalic%2A%2A%2Abold%20%20%60%3C--%20NONE%60%5Cn%5Cn_%2A%2Aitalic%2A%2A_bold%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%5Cn%5Cn%2A%2A_italic_%2A%2Abold%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%5Cn%5Cn%23%23%20At%20end%20of%20the%20word%3A%5Cn%5Cnitalic%2A%2A%2Abold%2A%2A%2A%20%20%60%3C--%20NONE%60%5Cn%5Cnitalic_%2A%2Abold%2A%2A_%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%5Cn%5Cnitalic%2A%2A_bold_%2A%2A%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D), similar commonmark [demo](https://spec.commonmark.org/dingus/?text=%23%23%20Full%20word%20wrap%3A%0A%0A***italicbold***%20%20%60%3C--%20OK%60%0A%0A_**italicbold**_%20%20%60%3C--%20OK%60%0A%0A**_italicbold_**%20%20%60%3C--%20OK%60%0A%0A%23%23%20Inside%20word%20wrap%3A%0A%0Aita***licbo***ld%20%20%60%3C--%20FAIL%20in%20MarkdownIt%2C%20OK%20here%60%0A%0Aita_**licbo**_ld%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%0A%0Aita**_licbo_**ld%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%0A%0A%23%23%20At%20start%20of%20the%20word%3A%0A%0A***italic***bold%20%20%60%3C--%20FAIL%20in%20MarkdownIt%2C%20OK%20here%60%0A%0A_**italic**_bold%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%0A%0A**_italic_**bold%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%0A%0A%23%23%20At%20end%20of%20the%20word%3A%0A%0Aitalic***bold***%20%20%60%3C--%20FAIL%20in%20MarkdownIt%2C%20OK%20here%60%0A%0Aitalic_**bold**_%20%20%60%3C--%20bold%3A%20OK%2C%20italic%3A%20FAIL%60%0A%0Aitalic**_bold_**%20%20%60%3C--%20bold%3A%20FAIL%2C%20italic%3A%20OK%60%0A)

### CODE REVIEW

**Comment by puzrin** [comment]
I think, this should be arranged a bit different.

1. Prior to push here, it worth try suggest those to commonmark spec as "missed cases". First, to minimize amount of diverged tests here. Second, formally, if commonmark has no official requirement, we should not follow it. If added to commonmark spec - we MUST pass those tests automatically.
2. It's not acceptabe to have broken tests in master - that will block development. This can stay in PR, or should be marked with `.skip()` for merge. I think, if nobody reported this problem several years, that's more edge case than fatal bug.
3. Tests location should be different, with separate runner like https://github.com/markdown-it/markdown-it/blob/test/markdown-it.js, to be able disable it. But again, prior to do this - consider suggest this test cases into commonmark spec.

**Comment by AlexanderSergan** [comment]
@puzrin Thanks for such clarification. I split combined test cases in atomic and moved it to separate file with `skip` meta. I'll try to find out in `commonmark` team if these tests are needed in `commonmark` repository. If so, you can merge this into your repo. Sounds good?

**Comment by puzrin** [comment]
Sure. I have feeling this should be in CM spec, but if they reject - i will find way to accomodate this into this repo (and, of cause, find a way to fix)

**Comment by AlexanderSergan** [comment]
@puzrin I got a clarification about this behavior:
> This is the result of intended and desired behavior. [Commonmark restricts intraword emphasis](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis) to asterisks which are less problematic than underscores, since the latter are too frequently encountered as a replacement for spaces, e.g. in file names.
> 
> [Babelmark](https://babelmark.github.io/?text=*+%60***+***%60%0A+++-+***bi***%0A+++-+n***bi***n%0A+++-+***bi***n%0A+++-+n***bi***%0A*+%60_**+**_%60%0A+++-+_**ib**_%0A+++-+n_**b**_n%0A+++-+_**b**_n+%0A+++-+n_**b**_+%0A*+%60**_+_**%60%0A+++-+**_bi_**%0A+++-+n**_i_**n%0A+++-+**_i_**n%0A+++-+n**_i_**%0A)
[link](https://github.com/commonmark/commonmark-spec/issues/590#issuecomment-504112960)
So, while underscore mark is not parsed inside of a word because of frequent usage as other logical mark, `***` mark is parsed as strong/em combo which is illustrated at demos attached to this PR overview.

Let's wait for answer about adding to test cases at commonmark. Thanks.

**Comment by rlidwka** [comment]
Is this still needed? As far as I can see, all these test cases are covered by commonmark spec in one way or another.

All tests should pass as of now.

**Comment by AlexanderSergan** [comment]
Thank you @rlidwka for the contributing to the latest release, the issue can be closed now.

**Pull request closed without merging**
