### PR TITLE
Update for latest CommonMark spec

### PR DESCRIPTION
**Pull request by kivikakk**
The spec has changed in a few minor ways; this brings markdown-it up to scratch.

### CODE REVIEW

**Comment by puzrin** [comment]
1. IMHO it worth ask @jgm to release 0.28 spec first. It would be confusing to use intermediate documents.
2. Some tests are broken in your PR. You need `make specsplit`

**Comment by kivikakk** [comment]
1. A good point. I'm happy to leave this PR open and wait until 0.28 lands; I'll happily update it for whatever other changes come in the meantime, I know there's still some discussions even I'd like to have resolved for the next version.
2. Ah, I didn't notice `specsplit` was what wrote out `good.txt`; thanks.

**Comment by puzrin** [comment]
I think it will be more easy, if we do all changes at our side. Just kick me when new spec version appears.

**Comment by kivikakk** [comment]
Sure thing!

**Pull request closed without merging**
